### PR TITLE
Add SECURITY.md

### PR DESCRIPTION
**Pull request by terrajobst**

### CODE REVIEW

**Comment by CZEMacLeod** [comment]
Since this project (and katana) are not aspnetcore or netcore - I think you might need to reword the first part.

**Comment by terrajobst** [comment]
@blowdart I assume the spirit applies here as well. Do we have wording for non-core bits?

**Comment by blowdart** [comment]
# Security Policy

## Reporting a Vulnerability

Security issues and bugs should be reported privately to the Microsoft Security Response Center (MSRC), either by emailing secure@microsoft.com or via the portal at https://msrc.microsoft.com.
You should receive a response within 24 hours. If for some reason you do not, please follow up via email to ensure we received your
original message. Further information, including the MSRC PGP key, can be found in the [MSRC Report an Issue FAQ](https://www.microsoft.com/en-us/msrc/faqs-report-an-issue).

Please do not open issues for anything you think might have a security implication.

**Comment by terrajobst** [comment]
Fixed

**Pull request merged**
