### PR TITLE
Add workflow to sync eng/common/templates from arcade

### PR DESCRIPTION
**Pull request by wtgodbe**
In the style of https://github.com/dotnet/spa-templates/pull/59 (with a touch of https://github.com/dotnet/spa-templates/pull/61). @dougbu is anything else needed on the github end to enable this workflow?

### CODE REVIEW

**Comment by dougbu** [comment]
> @dougbu is anything else needed on the github end to enable this workflow?

Align <https://github.com/aspnet/AspNetWebStack/settings/actions> w/ settings from <https://github.com/dotnet/aspnetcore/settings/actions>. Probably don't need the peter-evans mention in the list of allowed reusable workflows.

**Review by dougbu — APPROVED** [review]
Should be fine for now. Note however that this repo needs absolutely nothing from eng/common/ at the moment. That'll change as soon as we start extending internal builds to e.g. sign or create SBOMs.

**Comment by wtgodbe** [comment]
> Should be fine for now. Note however that this repo needs absolutely nothing from eng/common/ at the moment. That'll change as soon as we start extending internal builds to e.g. sign or create SBOMs.

I only added the sync for `/eng/common/templates`

**Comment by wtgodbe** [comment]
> Align https://github.com/aspnet/AspNetWebStack/settings/actions w/ settings from https://github.com/dotnet/aspnetcore/settings/actions. Probably don't need the peter-evans mention in the list of allowed reusable workflows.

Done

**Comment by dougbu** [comment]
> I only added the sync for `/eng/common/templates`

I know. We don't use anything from there either. The previous mention of pool-providers.yml didn't do anything because your pipeline didn't need or use the variables set in that file.

**Comment by wtgodbe** [comment]
> I know. We don't use anything from there either. The previous mention of pool-providers.yml didn't do anything because your pipeline didn't need or use the variables set in that file.

Wow, I must be losing my mind - I could have sworn I was using `eng\common\templates\jobs\codeql-build.yml`. I'm more inclined to just hold off on this until we actually need eng\common stuff in that case, and just add an arcade subscription at that point - thoughts?

**Comment by dougbu** [comment]
> I'm more inclined to just hold off on this until we actually need eng\common stuff in that case, and just add an arcade subscription at that point - thoughts?

Hmm, initially either was fine w/ me. But I seem to remember some parts of the Arcade templates e.g. steps that publish to the BAR require more than just YAML. Let's see what happens&hellip;

**Pull request closed without merging**
